### PR TITLE
Add AutoHotKey test executable

### PR DESCRIPTION
**Pull request by recvfrom**
I made this EXE using AutoHotKey 1.1.33.02 and it just returns right away, so it should be a good minimal EXE for testing, but it might still be too big / too slow to analyze... we'll see!

### CODE REVIEW

**Comment by williballenthin** [comment]
hm, yeah, runs for about four minutes which is a bit long. this is probably a good indication we should try to avoid processing AHK samples. 

@Ana06 @mr-tz @mike-hunhoff should we build in a first pass over file strings to filter out samples that we're unlikely to be able to process?

**Comment by mr-tz** [comment]
yes, sounds like a good plan

**Comment by mr-tz** [comment]
while at this, could work on moving the limitation from code to rules, see https://github.com/fireeye/capa/issues/390

**Comment by williballenthin** [comment]
wait for https://github.com/fireeye/capa/pull/591

**Pull request merged**
