### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by johnk3r**
https://github.com/fireeye/capa-rules/issues/239

### CODE REVIEW

**Comment by mr-tz** [comment]
Would you be able to provide a different sample than `bbff746a9436ec819b5ccbe84c36f9852e336091a7559d15c275460d5e612963.dll_` so we can test a little faster?
See https://github.com/fireeye/capa-testfiles/pull/67/checks?check_run_id=1883643726#step:8:816:
`capa ran for 633 seconds, please provide a different sample so we can test more quickly`

Side note: this shows that the changes in #66 work.

**Comment by mr-tz** [comment]
Thanks, I see `17264e3126a97c319a6a0c61e6da951e.dll_` in https://github.com/fireeye/capa-rules/pull/258. Where is  `3242434f9894f1d6e706d21a5e544659cf429b361a28e147b7fef9a08edc56d5.dll_` used?

**Comment by johnk3r** [comment]
Sorry, I forgot to remove this file.

**Comment by mr-tz** [comment]
Thanks!

**Pull request merged**
