### PR TITLE
add 9bca6b99e7981208af4c7925b96fb9cf

### PR DESCRIPTION
**Pull request by williballenthin**
supports https://github.com/fireeye/capa-rules/pull/276

### CODE REVIEW

**Comment by williballenthin** [comment]
smallest VB file i could find on VT easily

**Comment by mr-tz** [comment]
Are you sure, you can't find a smaller file? 😉

**Comment by williballenthin** [comment]
image
??? what is happening?

**Comment by williballenthin** [comment]
lets see what happens if we merge. if we get the empty file, i'll re-upload.

**Comment by williballenthin** [comment]
looks ok?

image

**Comment by mr-tz** [comment]
looks like an UI issue, @re-fox encountered this before, so let's keep an eye out for this

**Comment by re-fox** [comment]
I wasn't able to figure out the root cause.  I thought it might be a result of uploading from a shared volume (local instance was running in a container), but after forking the repo and trying again it worked.  So I'm not entirely sure.

**Pull request merged**
