### PR TITLE
Add example for hash-data-using-fnv

### PR DESCRIPTION
**Pull request by recvfrom**
From: https://blog.morphisec.com/crystalbit-apple-double-dll-hijack

NOTE: it takes over 2 GB of memory for capa to analyze this. I had to exit out of Ghidra in my VM because capa kept getting killed x_x

### CODE REVIEW

**Comment by williballenthin** [comment]
> NOTE: it takes over 2 GB of memory for capa to analyze this.

yikes.

while i appreciate the effort to updating the examples, i'm hesitant to reference a sample that takes so many resources to analyze (well, maybe capa should just be faster ;-) ). let me take a peek and try to figure out why this performs so poorly. otherwise, i think i'd like to keep an eye out for more lightweight examples.

**Comment by recvfrom** [comment]
@williballenthin understood - I'm using python 2.7, so hopefully it's isolated to that and maybe an older version of vivisect? 🤞

**Comment by williballenthin** [comment]
its taking IDA multiple minutes to load this sample, too. which is fascinating in and of itself. code looks pretty normal so far, maybe there are just a ton of instructions? research in progress...

**Comment by williballenthin** [comment]
so the file only has around 500 functions, which isn't that many.
however, there are many functions that are huge. see the screenshot below. one function is 0xE5FF2 bytes long :-O no wonder IDA (and other tools) take a long time analyzing this.
im not sure if these are junk functions or implement anything useful. in any case, its an effective anti-analysis technique.

image

**Comment by recvfrom** [comment]
Ah, interesting! well, my apologies for the capa testing process resource exhaustion DoS attempt lol

**Pull request closed without merging**
