### PR TITLE
Added two reference files for goparser

### PR DESCRIPTION
**Pull request by jaredscottwilson**
Added examples with the following MD5s:
      - ebfba63891471ced641b60e0403777da
      - 03ae008aa48e52d32517a60e2ce1a1d2

### CODE REVIEW

**Comment by williballenthin** [comment]
typically, we'd love as many references as possible; however, these are go binaries and therefore quite large. this means they'll have an outsized effect on the runtime of our unit tests. therefore, would you might adding only a single test file (14d3... is the smaller one)?

@mr-tz can you double check my claims here?

**Comment by mr-tz** [comment]
yes, unfortunately both files time out 😐

**Comment by jaredscottwilson** [comment]
Shoot. Hmm. Ok, I'll look at all the live sample results and find the smallest.

**Comment by jaredscottwilson** [comment]
2.87 MB is the smallest I have in malware zoos... I'll see if I can compress something small haha.

**Comment by williballenthin** [comment]
> I'll see if I can compress something small haha.

please don't compress the file before upload - the files should in PE format with the repo so capa can process them. go binaries are large by design, so its nice to have the smallest binary but we're only going to get so far.

**Comment by jaredscottwilson** [comment]
Right, sorry, I wasn't clear. I meant pack* rather than compress. Pack something really small with the hopes the small size of the source is a parallel to the size of the final packed version. That being the case, it looks like the 2.87 MB is the smallest it goes. Any suggestions?

**Comment by mr-tz** [comment]
Let's see if we can tweak the CI checks if needed.

**Comment by mr-tz** [comment]
For the filename please follow https://github.com/fireeye/capa-testfiles#naming-conventions

**Comment by mr-tz** [comment]
As a workaround should we add a file that lists samples which are excluded from run-time checks?

**Pull request merged**
